### ISSUE TITLE
环境搭建

### ISSUE THREAD

**Issue by KaitaoQiu** [WU-Kave/xiaohongshu-crawl-comments-user#1]
请问环境搭建需要什么配置吗？我按照网络上的方法，搭建了appium，但是还是没跑通，还有什么需要做的吗？谢谢楼主

**Comment by luanshils** [comment]
我表示我也搭建了，它就是不跑

**Comment by KaitaoQiu** [comment]
我跑通了，但是需要修改很多东西，因为label还是什么的地方需要修改很多，而且会随时间/app版本变化

**Comment by luanshils** [comment]
可以共享一下不


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WU-Kave/xiaohongshu-crawl-comments-user"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月17日(星期天) 下午3:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WU-Kave/xiaohongshu-crawl-comments-user] 环境搭建 (Issue #1)





 
我跑通了，但是需要修改很多东西，因为label还是什么的地方需要修改很多，而且会随时间/app版本变化

**Comment by KaitaoQiu** [comment]
> 可以共享一下不
> 
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 
> 发件人:                                                                                                                        "WU-Kave/xiaohongshu-crawl-comments-user"                                                                                    ***@***.***&gt;;
> 
> 发送时间:&nbsp;2023年9月17日(星期天) 下午3:21
> 
> ***@***.***&gt;;
> 
> ***@***.******@***.***&gt;;
> 
> 主题:&nbsp;Re: [WU-Kave/xiaohongshu-crawl-comments-user] 环境搭建 (Issue #1)
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
>  
> 
> 我跑通了，但是需要修改很多东西，因为label还是什么的地方需要修改很多，而且会随时间/app版本变化
> 
>  
> 
> —
> 
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> You are receiving this because you commented.Message ID: ***@***.***&gt;

可以倒是可以，不过你肯定没法用，因为那玩意儿不固定，每次重启模拟器，每个按键的id 都会变，你可以看看源码

**Comment by luanshils** [comment]
好的，我学习一下大佬改的代码


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WU-Kave/xiaohongshu-crawl-comments-user"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月17日(星期天) 下午3:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WU-Kave/xiaohongshu-crawl-comments-user] 环境搭建 (Issue #1)





  
可以共享一下不
 
------------------&nbsp;原始邮件&nbsp;------------------
 
发件人:                                                                                                                        "WU-Kave/xiaohongshu-crawl-comments-user"                                                                                    @.***&gt;;
 
发送时间:&nbsp;2023年9月17日(星期天) 下午3:21
 
@.***&gt;;
 
@.@.&gt;;
 
主题:&nbsp;Re: [WU-Kave/xiaohongshu-crawl-comments-user] 环境搭建 (Issue #1)
 
我跑通了，但是需要修改很多东西，因为label还是什么的地方需要修改很多，而且会随时间/app版本变化
 
—
 
Reply to this email directly, view it on GitHub, or unsubscribe.
 
You are receiving this because you commented.Message ID: @.***&gt;
  
可以倒是可以，不过你肯定没法用，因为那玩意儿不固定，每次重启模拟器，每个按键的id 都会变，你可以看看源码

**Comment by WU-Kave** [comment]
@luanshils 抱歉，我很久没看过这个了，不能给出准确答复了。

难点主要是adb连接问题。

补充：
1. 配置项 `appActivity` 是启动页面，我配置的是首页，如果没有登录是没法进首页的。
2. 爬虫原理是通过元素 ID 值定位到元素，再获取文本值。距离我发布已经过去4个多月了，app 经过了版本更新之后元素 ID 值不一定对得上。

这是我之前的一些参考资料：
- [APP自动化测试之appium连接真机启动app](https://www.jianshu.com/p/4e763b511937)
- [Appium使用教程（七）——获取appPackage和appActivity](https://blog.csdn.net/MTbaby/article/details/78676477) （推荐方法一）
